# Use the official Eclipse Temurin image for a stable Java environment
FROM eclipse-temurin:21-jdk-focal

# Set the working directory inside the container
WORKDIR /app

# Copy the Gradle wrapper files and source code
COPY gradlew .
COPY gradle gradle
COPY build.gradle.kts .
COPY settings.gradle.kts .
COPY src src

# Make the wrapper executable (needed for Linux environment in Render)
RUN chmod +x gradlew

# Build the Ktor application and install it (creates the build/install directory)
RUN ./gradlew installDist

# Use the lighter JRE for the final run stage
FROM eclipse-temurin:21-jre-focal

# Set the working directory
WORKDIR /app

# Copy only the installed application from the build stage
COPY --from=0 /app/build/install/CritterTrack-Server CritterTrack-Server

# Set the entry point to run your application's startup script
# The script is generated by the installDist task
ENTRYPOINT ["/app/CritterTrack-Server/bin/CritterTrack-Server"]

# Expose the default Ktor port (8080 or the one read from PORT)
EXPOSE 8080